# Query 3 - List each country alongside the average height and 
# weight of its athletes (sorted by the average height). 

PREFIX walls: <http://wallscope.co.uk/ontology/olympics/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?countryCode
       (AVG(?height) As ?avgHeight)
       (AVG(?weight) As ?avgWeight)
WHERE {
 ?noc dbo:ground ?team ;
      rdfs:label ?countryCode .
 
 ?athlete rdf:type   foaf:Person ;
          dbo:team   ?team ;
          dbo:height ?height ;
          dbo:weight ?weight .
}
GROUP BY ?countryCode
ORDER BY DESC(?avgHeight)
