## Query 2 - List the names of every athlete, with at least one medal, alongside their total number of medals (sorted by the number of medals).

SPARQL

PREFIX walls: <http://wallscope.co.uk/ontology/olympics/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?name (COUNT(?name) As ?noOfMedals)
WHERE {
  ?instance walls:athlete ?athlete ;
            walls:medal   ?medal .
  ?athlete  rdfs:label    ?name .
}
GROUP BY ?name
ORDER BY DESC(?noOfMedals)
